# Generated by Django 3.0.7 on 2020-06-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='quote',
            field=models.TextField(),
        ),
    ]
