# Generated by Django 3.0.7 on 2020-06-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecard_app', '0002_auto_20200628_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='quote',
            field=models.CharField(max_length=250),
        ),
    ]
