# Generated by Django 3.0.7 on 2020-06-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecard_app', '0003_auto_20200628_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='quote3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=80)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='quotes2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=80)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
