# Generated by Django 3.0.7 on 2020-06-28 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecard_app', '0004_quote3_quotes2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quote3',
            new_name='quotes3',
        ),
    ]
